<header>
      <nav class="navbar navbar-expand-md navbar-light fixed-top" style="background-color:white;">
        <a class="navbar-brand" href="index.php">
          <img src="img/logos/beco_logo.png" width="30" height="30" class="d-inline-block align-top">
          BECO
        </a>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="sobrenos.php">Sobre Nos</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="encontros.php">Encontros </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="faleConosco.php">Fale Conosco</a>
            </li>
          </ul>
        </div>
        <a class="navbar-brand" href="https://www.facebook.com/becolel/">
          <img src="img/logos/facebook.png" width="30" height="30" class="d-inline-block align-center">
        </a>
        <a class="navbar-brand" href="https://www.instagram.com/becolel/">
          <img src="img/logos/instagram.png" width="30" height="30" class="d-inline-block align-center">
        </a>
        <a class="navbar-brand" href="https://arq.ifsp.edu.br/portal/">
          <img src="img/logos/logo_ifsp.png" width="150" height="40" class="d-inline-block align-center">
        </a>
      </nav>
      </div>
    </header>